  public void setYRangeParams() throws Exception {
    assertPlotParam("yrange","[0:1]");
    assertPlotParam("yrange", "[:]");
    assertPlotParam("yrange", "[:0]");
    assertPlotParam("yrange", "[:42]");
    assertPlotParam("yrange", "[:-42]");
    assertPlotParam("yrange", "[:0.8]");
    assertPlotParam("yrange", "[:-0.8]");
    assertPlotParam("yrange", "[:42.4]");
    assertPlotParam("yrange", "[:-42.4]");
    assertPlotParam("yrange", "[:4e4]");
    assertPlotParam("yrange", "[:-4e4]");
    assertPlotParam("yrange", "[:4e-4]");
    assertPlotParam("yrange", "[:-4e-4]");
    assertPlotParam("yrange", "[:4.2e4]");
    assertPlotParam("yrange", "[:-4.2e4]");
    assertPlotParam("yrange", "[0:]");
    assertPlotParam("yrange", "[5:]");
    assertPlotParam("yrange", "[-5:]");
    assertPlotParam("yrange", "[0.5:]");
    assertPlotParam("yrange", "[-0.5:]");
    assertPlotParam("yrange", "[10.5:]");
    assertPlotParam("yrange", "[-10.5:]");
    assertPlotParam("yrange", "[10e5:]");
    assertPlotParam("yrange", "[-10e5:]");
    assertPlotParam("yrange", "[10e-5:]");
    assertPlotParam("yrange", "[-10e-5:]");
    assertPlotParam("yrange", "[10.1e-5:]");
    assertPlotParam("yrange", "[-10.1e-5:]");
    assertPlotParam("yrange", "[-10.1e-5:-10.1e-6]");
    assertInvalidPlotParam("yrange", "[33:system('touch /tmp/poc.txt')]");
    assertInvalidPlotParam("y2range", "[42:%0a[33:system('touch /tmp/poc.txt')]");
  }